In [69]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
from pydataset import data
import pandas as pd
import numpy as np
import acquire
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
print('Success')

Success


## Evaluate (by hand) the model's performance.


|               | actual cat | actual dog |
|:------------  |-----------:|-----------:|
| predicted cat |         34 |          7 |
| predicted dog |         13 |         46 |

* In the context of this problem, what is a false positive?
  - Answer: Assuming we are evaluating whether an animal is a dog or not, a false positive would be classifiying an animal as a dog when it was not a dog (either a cat or some other animal)
* In the context of this problem, what is a false negative?
  - Answer: Assuming we are evaluating whether an animal is a dog or not, a false negative would be classifiying an animal as not a dog (or a cat) when it really was a dog
* How would you describe this model?
  - Answer: 

## C3 
Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here (C3.csv).

In [70]:
c3 = pd.read_csv('c3.csv')
c3.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

* An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [71]:
# Recall is the best evaluation metric for this task 

# Subsect the data to only pull the results where there was an actual defect
c3defect = c3[c3.actual == 'Defect']

# Recall = TP / (TP + FN)

# Create a dictionary of the models' accuracy where the actual value is equal to the predicated value and find which model 
# has the heightest recall
models = {'model_1': (c3defect.model1 == c3defect.actual).mean(),
'model_2' : (c3defect.model2 == c3defect.actual).mean(),
'model_3' : (c3defect.model3 == c3defect.actual).mean()
}

print(models)
max(models, key=models.get)

{'model_1': 0.5, 'model_2': 0.5625, 'model_3': 0.8125}


'model_3'

### The most accurate model 

In [72]:
accuracy = {'model_1': (c3.model1 == c3.actual).mean(),
'model_2' : (c3.model2 == c3.actual).mean(),
'model_3' : (c3.model3 == c3.actual).mean()
}

print(accuracy)
max(accuracy, key=accuracy.get)

{'model_1': 0.95, 'model_2': 0.56, 'model_3': 0.555}


'model_1'

* Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [73]:
# This is wrong need to adjust it to subset = model1-3 == defect .mean()

c3['model1_TP'] = (c3['actual'] == 'Defect') & (c3['model1'] == 'Defect')
c3['model2_TP'] = (c3['actual'] == 'Defect') & (c3['model2'] == 'Defect')
c3['model3_TP'] = (c3['actual'] == 'Defect') & (c3['model3'] == 'Defect')

c3['model1_FP'] = (c3['actual'] == 'No Defect') & (c3['model1'] == 'Defect')
c3['model2_FP'] = (c3['actual'] == 'No Defect') & (c3['model1'] == 'Defect')
c3['model3_FP'] = (c3['actual'] == 'No Defect') & (c3['model1'] == 'Defect')

percision = {'model_1' : c3['model1_TP'].sum()/(c3['model1_FP'].sum() + c3['model1_TP'].sum()) * 100,
'model_2' : c3['model2_TP'].sum()/(c3['model2_FP'].sum() + c3['model2_TP'].sum()) * 100,
'model_3' :c3['model3_TP'].sum()/(c3['model3_FP'].sum() + c3['model3_TP'].sum()) * 100}
print(percision)
max(percision, key=percision.get)

{'model_1': 80.0, 'model_2': 81.81818181818183, 'model_3': 86.66666666666667}


'model_3'

## Gives You Paws ™

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

Several models have already been developed with the data, and you can find their results here (gives_you_paws.csv).

Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In [74]:
paws = pd.read_csv('gives_you_paws.csv')
paws.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [75]:
paws['base_line'] = 'dog'

* In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [76]:
accuracy = {'model_1': (paws.model1 == paws.actual).mean(),
'model_2' : (paws.model2 == paws.actual).mean(),
'model_3' : (paws.model3 == paws.actual).mean(),
'model_4' : (paws.model4 == paws.actual).mean(),
'base_line' : (paws.base_line == paws.actual).mean(),
}
print(accuracy)
print()
print(f"The model with the heightest accuracy - {max(accuracy, key=accuracy.get)}")


{'model_1': 0.8074, 'model_2': 0.6304, 'model_3': 0.5096, 'model_4': 0.7426, 'base_line': 0.6508}

The model with the heightest accuracy - model_1


* Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? 

In [77]:
dog = paws[paws['actual'] == 'dog']

dog_accuracy = {'model_1': (dog.model1 == dog.actual).mean(),
'model_2' : (dog.model2 == dog.actual).mean(),
'model_3' : (dog.model3 == dog.actual).mean(),
'model_4' : (dog.model4 == dog.actual).mean(),
}
print(dog_accuracy)
print()
print(f"Accuraccy is the best measure for Phase 1 and the model with the heightest accuracy is {max(dog_accuracy, key=dog_accuracy.get)}")



{'model_1': 0.803318992009834, 'model_2': 0.49078057775046097, 'model_3': 0.5086047940995697, 'model_4': 0.9557467732022127}

Accuraccy is the best measure for Phase 1 and the model with the heightest accuracy is model_4


* For Phase II?

In [78]:
# Recall = TP/TP + FN
dog['model1TP'] = dog.model1 == dog.actual
dog['model2TP'] = dog.model2 == dog.actual
dog['model3TP'] = dog.model3 == dog.actual
dog['model4TP'] = dog.model4 == dog.actual

dog['model1FN'] = (dog.model1 == 'cat') & (dog.actual == 'dog')
dog['model2FN'] = (dog.model2 == 'cat') & (dog.actual == 'dog')
dog['model3FN'] = (dog.model3 == 'cat') & (dog.actual == 'dog')
dog['model4FN'] = (dog.model4 == 'cat') & (dog.actual == 'dog')

dog_recall = {"model1": dog['model1TP'].sum()/(dog['model1FN'].sum() + dog['model1TP'].sum()),
              "model2": dog['model2TP'].sum()/(dog['model2FN'].sum() + dog['model2TP'].sum()),
              "model3": dog['model3TP'].sum()/(dog['model3FN'].sum() + dog['model3TP'].sum()),
              "model4": dog['model4TP'].sum()/(dog['model4FN'].sum() + dog['model4TP'].sum())
             }
dog_recall

{'model1': 0.803318992009834,
 'model2': 0.49078057775046097,
 'model3': 0.5086047940995697,
 'model4': 0.9557467732022127}

* Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? 

In [79]:
cat = paws[paws['actual'] == 'cat']

cat_accuracy = {'model_1': (cat.model1 == cat.actual).mean(),
'model_2' : (cat.model2 == cat.actual).mean(),
'model_3' : (cat.model3 == cat.actual).mean(),
'model_4' : (cat.model4 == cat.actual).mean(),
}
print(cat_accuracy)
print()
print(f"Accuraccy is the best measure for Phase 1 and the model with the heightest accuracy is {max(cat_accuracy, key=cat_accuracy.get)}")



{'model_1': 0.8150057273768614, 'model_2': 0.8906071019473081, 'model_3': 0.5114547537227949, 'model_4': 0.34536082474226804}

Accuraccy is the best measure for Phase 1 and the model with the heightest accuracy is model_2


* For Phase II?

In [80]:
# Recall = TP/TP + FN
cat['model1TP'] = cat.model1 == cat.actual
cat['model2TP'] = cat.model2 == cat.actual
cat['model3TP'] = cat.model3 == cat.actual
cat['model4TP'] = cat.model4 == cat.actual

cat['model1FN'] = (cat.model1 == 'dog') & (cat.actual == 'cat')
cat['model2FN'] = (cat.model2 == 'dog') & (cat.actual == 'cat')
cat['model3FN'] = (cat.model3 == 'dog') & (cat.actual == 'cat')
cat['model4FN'] = (cat.model4 == 'dog') & (cat.actual == 'cat')

cat_recall = {"model1": cat['model1TP'].sum()/(cat['model1FN'].sum() + cat['model1TP'].sum()),
              "model2": cat['model2TP'].sum()/(cat['model2FN'].sum() + cat['model2TP'].sum()),
              "model3": cat['model3TP'].sum()/(cat['model3FN'].sum() + cat['model3TP'].sum()),
              "model4": cat['model4TP'].sum()/(cat['model4FN'].sum() + cat['model4TP'].sum())
             }
cat_recall

{'model1': 0.8150057273768614,
 'model2': 0.8906071019473081,
 'model3': 0.5114547537227949,
 'model4': 0.34536082474226804}

* Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

In [81]:
paws_accuracy = {
'model1': accuracy_score(paws['actual'], paws['model1']),
'model2' : accuracy_score(paws['actual'], paws['model2']),
'model3' : accuracy_score(paws['actual'], paws['model3']),
'model4': accuracy_score(paws['actual'], paws['model4'])
}

print(f" Highest Accuracy - {max(paws_accuracy, key=paws_accuracy.get)} with a score of {max(paws_accuracy.values())}")

 Highest Accuracy - model1 with a score of 0.8074


In [82]:
paws_percision = {
'model1': precision_score(paws['actual'], paws['model1'],average='macro'),
'model2' : precision_score(paws['actual'], paws['model2'], average='macro'),
'model3' : precision_score(paws['actual'], paws['model3'], average='macro'),
'model4': precision_score(paws['actual'], paws['model4'], average='macro')
}

print(paws_percision)
print(f" Highest Percision - {max(paws_percision, key=paws_percision.get)} with a score of {max(paws_percision.values())}")

{'model1': 0.7898980051430666, 'model2': 0.6886493880609905, 'model3': 0.5091175333635416, 'model4': 0.7692387230558727}
 Highest Percision - model1 with a score of 0.7898980051430666


In [83]:


dog_reacll = {
'model1': recall_score(dog['actual'], dog['model1'], average='micro'),
'model2' : recall_score(dog['actual'], dog['model2'], average='micro'),
'model3' : recall_score(dog['actual'], dog['model3'], average='micro'),
'model4': recall_score(dog['actual'], dog['model4'], average='micro')
}

print(f" Highest Recall - {max(dog_reacll, key=dog_reacll.get)} with a score of {max(dog_reacll.values())}")

 Highest Recall - model4 with a score of 0.9557467732022127


In [84]:
paws_reacll = {
'model1': recall_score(paws['actual'], paws['model1'],average='macro'),
'model2' : recall_score(paws['actual'], paws['model2'], average='macro'),
'model3' : recall_score(paws['actual'], paws['model3'], average='macro'),
'model4': recall_score(paws['actual'], paws['model4'], average='macro')
}

print(f" Highest Recall - {max(paws_reacll, key=paws_reacll.get)} with a score of {max(paws_reacll.values())}")

 Highest Recall - model1 with a score of 0.8091623596933477


In [85]:
print(classification_report(paws['actual'], paws['model1']))


              precision    recall  f1-score   support

         cat       0.69      0.82      0.75      1746
         dog       0.89      0.80      0.84      3254

    accuracy                           0.81      5000
   macro avg       0.79      0.81      0.80      5000
weighted avg       0.82      0.81      0.81      5000



## Logistic Regression
In this exercise, we'll continue working with the titanic dataset and building logistic regression models. Throughout this exercise, be sure you are training, evaluation, and comparing models on the train and validate datasets. The test dataset should only be used for your final model.

For all of the models you create, choose a threshold that optimizes for accuracy.

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import env
import prepare
import acquire

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

titanic = acquire.get_titanic_data()
titanic = prepare.prep_titanic_exercise()
titanic['child'] = titanic['age'] <= 12
titanic.dropna(inplace=True)
titanic.head(1)

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
1             1         1       1  female  38.0      1      0  71.2833   

  embarked  class deck embark_town  alone  C  Q  S  impute_age  child  
1        C  First    C   Cherbourg      0  1  0  0        38.0  False

* Start by defining your baseline model.

In [87]:
titanic['base_line_survived'] = 0
titanic_baseline = titanic[['survived' ,'base_line_survived']]
baseline_accuracy = (titanic_baseline.survived == titanic_baseline.base_line_survived).mean()
print(f"Our baseline model's accuracy of saying every passanger died is {baseline_accuracy}")

Our baseline model's accuracy of saying every passanger died is 0.3241758241758242


* Create another model that includes age in addition to fare and pclass. Does this model perform better than your baseline?

In [88]:
X = titanic[['pclass','age','fare']]
y = titanic[['survived']]
X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

train:  (88, 3) , validate:  (39, 3) , test:  (55, 3)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


In [89]:
# from sklearn.linear_model import LogisticRegression
logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)

Coefficient: 
 [[-0.03645626 -0.02832494  0.00019455]]
Intercept: 
 [1.77084362]


In [90]:
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))

print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of Logistic Regression classifier on training set: 0.69
[[ 2 26]
 [ 1 59]]
              precision    recall  f1-score   support

           0       0.67      0.07      0.13        28
           1       0.69      0.98      0.81        60

    accuracy                           0.69        88
   macro avg       0.68      0.53      0.47        88
weighted avg       0.69      0.69      0.60        88



* Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model.

In [91]:
X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

train:  (88, 5) , validate:  (39, 5) , test:  (55, 5)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


In [92]:
logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)

Coefficient: 
 [[-1.34493711e-01 -2.19663529e-02 -8.36342411e-04  1.34714090e+00
  -1.34697243e+00]]
Intercept: 
 [2.11410823]


In [93]:
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of Logistic Regression classifier on training set: 0.81
[[23  5]
 [12 48]]
              precision    recall  f1-score   support

           0       0.66      0.82      0.73        28
           1       0.91      0.80      0.85        60

    accuracy                           0.81        88
   macro avg       0.78      0.81      0.79        88
weighted avg       0.83      0.81      0.81        88



* Try out other combinations of features and models.

In [94]:
X = titanic[['pclass', 'child']]
y = titanic[['survived']]

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

train:  (88, 2) , validate:  (39, 2) , test:  (55, 2)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


In [95]:
logit1 = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit1.fit(X_train, y_train)
print('Coefficient: \n', logit1.coef_)
print('Intercept: \n', logit1.intercept_)

Coefficient: 
 [[0.10229889 0.12220898]]
Intercept: 
 [0.64210995]


In [96]:
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit1.score(X_train, y_train)))

[[23  5]
 [12 48]]
              precision    recall  f1-score   support

           0       0.66      0.82      0.73        28
           1       0.91      0.80      0.85        60

    accuracy                           0.81        88
   macro avg       0.78      0.81      0.79        88
weighted avg       0.83      0.81      0.81        88

Accuracy of Logistic Regression classifier on training set: 0.68


In [97]:
X = titanic[['pclass', 'sex', 'age']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

train:  (88, 4) , validate:  (39, 4) , test:  (55, 4)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


In [98]:
logit2 = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit2.fit(X_train, y_train)
print('Coefficient: \n', logit2.coef_)
print('Intercept: \n', logit2.intercept_)

Coefficient: 
 [[-0.09976637 -0.02139931  1.34299326 -1.34299709]]
Intercept: 
 [1.97617782]


In [99]:
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
y_pred = logit2.predict(X_train)
y_pred_proba = logit2.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit2.score(X_train, y_train)))

[[23  5]
 [12 48]]
              precision    recall  f1-score   support

           0       0.66      0.82      0.73        28
           1       0.91      0.80      0.85        60

    accuracy                           0.81        88
   macro avg       0.78      0.81      0.79        88
weighted avg       0.83      0.81      0.81        88

Accuracy of Logistic Regression classifier on training set: 0.76


In [100]:
X = titanic[['pclass', 'sex', 'child']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

train:  (88, 4) , validate:  (39, 4) , test:  (55, 4)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


In [101]:
logit3 = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit3.fit(X_train, y_train)
print('Coefficient: \n', logit3.coef_)
print('Intercept: \n', logit3.intercept_)

Coefficient: 
 [[-0.00691075  0.43340434  1.37490414 -1.3748304 ]]
Intercept: 
 [1.11277333]


In [102]:
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
y_pred = logit3.predict(X_train)
y_pred_proba = logit3.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit3.score(X_train, y_train)))

[[21  7]
 [14 46]]
              precision    recall  f1-score   support

           0       0.60      0.75      0.67        28
           1       0.87      0.77      0.81        60

    accuracy                           0.76        88
   macro avg       0.73      0.76      0.74        88
weighted avg       0.78      0.76      0.77        88

Accuracy of Logistic Regression classifier on training set: 0.81


* Use you best 3 models to predict and evaluate on your validate sample.

In [103]:
# Model 1
X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)


print('Accuracy of Logistic Regression classifier on validate set: {:.2f}'
     .format(logit.score(X_validate, y_validate)))

Accuracy of Logistic Regression classifier on validate set: 0.82


In [104]:
# Model 2
X = titanic[['pclass', 'sex', 'age']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)


print('Accuracy of Logistic Regression classifier on validate set: {:.2f}'
     .format(logit.score(X_validate, y_validate)))


Accuracy of Logistic Regression classifier on validate set: 0.82


In [105]:
# Model 3
X = titanic[['pclass', 'sex', 'child']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)


print('Accuracy of Logistic Regression classifier on validate set: {:.2f}'
     .format(logit.score(X_validate, y_validate)))



Accuracy of Logistic Regression classifier on validate set: 0.79


* Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train?

In [106]:
# Model 2
X = titanic[['pclass', 'sex', 'age']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

logit = LogisticRegression(C=1, random_state=222, intercept_scaling=1, solver='lbfgs')
logit.fit(X_train, y_train)


print('Accuracy of Logistic Regression classifier on validate set: {:.2f}'
     .format(logit.score(X_test, y_test)))
print("The Accuracy score increased by 1% compared to validate")

Accuracy of Logistic Regression classifier on validate set: 0.71
The Accuracy score increased by 1% compared to validate


* Bonus1 How do different strategies for handling the missing values in the age column affect model performance?

* Bonus2: How do different strategies for encoding sex affect model performance?

* Bonus3: scikit-learn's LogisticRegression classifier is actually applying a regularization penalty to the coefficients by default. This penalty causes the magnitude of the coefficients in the resulting model to be smaller than they otherwise would be. This value can be modified with the C hyper parameter. Small values of C correspond to a larger penalty, and large values of C correspond to a smaller penalty.

Try out the following values for C and note how the coefficients and the model's performance on both the dataset it was trained on and on the validate split are affected.

C= .01 , .1 , 1 , 10 , 100 , 1000

* Bonus Bonus: how does scaling the data interact with your choice of C?

# Decision Tree

In this exercise, we'll continue working with the titanic dataset and building logistic regression models. Throughout this exercise, be sure you are training, evaluation, and comparing models on the train and validate datasets. The test dataset should only be used for your final model.

* Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [107]:
from sklearn.tree import DecisionTreeClassifier

X = titanic[['pclass', 'sex', 'child']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

clf = DecisionTreeClassifier(max_depth=2, random_state=222)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)
y_pred[0:5]
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [1.        , 0.        ],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.63414634, 0.36585366],
       [0.63414634, 0.36585366],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.

* Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [108]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of Decision Tree classifier on training set: 0.82
[[27  1]
 [15 45]]
              precision    recall  f1-score   support

           0       0.64      0.96      0.77        28
           1       0.98      0.75      0.85        60

    accuracy                           0.82        88
   macro avg       0.81      0.86      0.81        88
weighted avg       0.87      0.82      0.82        88



* Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

* Run through steps 2-4 using a different max_depth value.

In [109]:
X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

clf = DecisionTreeClassifier(max_depth=2, random_state=222)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)
y_pred[0:5]
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

train:  (88, 5) , validate:  (39, 5) , test:  (55, 5)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)


array([[0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [1.        , 0.        ],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.65      , 0.35      ],
       [0.65      , 0.35      ],
       [0.02325581, 0.97674419],
       [0.02325581, 0.97674419],
       [0.

In [110]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of Decision Tree classifier on training set: 0.83
[[27  1]
 [14 46]]
              precision    recall  f1-score   support

           0       0.66      0.96      0.78        28
           1       0.98      0.77      0.86        60

    accuracy                           0.83        88
   macro avg       0.82      0.87      0.82        88
weighted avg       0.88      0.83      0.84        88



In [111]:
X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)

clf = DecisionTreeClassifier(max_depth=5, random_state=222)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)
y_pred_proba = clf.predict_proba(X_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

train:  (88, 5) , validate:  (39, 5) , test:  (55, 5)
train:  (88, 1) , validate:  (39, 1) , test:  (55, 1)
Accuracy of Decision Tree classifier on training set: 0.90
[[24  4]
 [ 5 55]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        28
           1       0.93      0.92      0.92        60

    accuracy                           0.90        88
   macro avg       0.88      0.89      0.88        88
weighted avg       0.90      0.90      0.90        88



* Which performs better on your in-sample data?
  - Answer: The one with the lower threshold

# Random Forest

* Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 20.

In [112]:
from sklearn.ensemble import RandomForestClassifier

X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=1,
                            n_estimators=100,
                            max_depth=20, 
                            random_state=222)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, random_state=222)

* Evaluate your results using the model score, confusion matrix, and classification report.

In [113]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_validate, y_validate)))

Accuracy of Decision Tree classifier on training set: 0.90
[[24  4]
 [ 5 55]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        28
           1       0.93      0.92      0.92        60

    accuracy                           0.90        88
   macro avg       0.88      0.89      0.88        88
weighted avg       0.90      0.90      0.90        88

Accuracy of random forest classifier on test set: 0.74


* Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

* Run through steps increasing your min_samples_leaf to 5 and decreasing your max_depth to 3.

In [114]:
from sklearn.ensemble import RandomForestClassifier

X = titanic[['pclass','age','fare', 'sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .30, 
                                                                      random_state = 222, 
                                                                      stratify=y.survived)


X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.3, 
                                                            random_state = 222, 
                                                            stratify=y_train_validate)

rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=5,
                            n_estimators=100,
                            max_depth=3, 
                            random_state=222)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, min_samples_leaf=5, random_state=222)

* What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?

In [115]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of Decision Tree classifier on training set: 0.90
[[24  4]
 [ 5 55]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        28
           1       0.93      0.92      0.92        60

    accuracy                           0.90        88
   macro avg       0.88      0.89      0.88        88
weighted avg       0.90      0.90      0.90        88



In [116]:
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_validate, y_validate)))

Accuracy of random forest classifier on test set: 0.77


* After making a few models, which one has the best performance (or closest metrics) on both train and validate?

# K-Nearest Neighbor

* Fit a K-Nearest Neighbors classifier to your training sample and transform (i.e. make predictions on the training sample)

In [117]:
from sklearn.neighbors import KNeighborsClassifier

X = titanic[['pclass','age','fare','sibsp','parch']]
y = titanic[['survived']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)

X_train.head()

pclass   age      fare  sibsp  parch
123       2  32.5   13.0000      0      0
689       1  15.0  211.3375      0      1
174       1  56.0   30.6958      0      0
88        1  23.0  263.0000      3      2
712       1  48.0   52.0000      1      0

* Evaluate your results using the model score, confusion matrix, and classification report.

In [120]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_train)
y_pred_proba = knn.predict_proba(X_train)
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of KNN classifier on training set: 0.72
[[18 28]
 [ 7 74]]
              precision    recall  f1-score   support

           0       0.72      0.39      0.51        46
           1       0.73      0.91      0.81        81

    accuracy                           0.72       127
   macro avg       0.72      0.65      0.66       127
weighted avg       0.72      0.72      0.70       127



* Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [121]:
knn = KNeighborsClassifier(n_neighbors=10, weights='uniform')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_train)
y_pred_proba = knn.predict_proba(X_train)
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of KNN classifier on training set: 0.72
[[19 27]
 [ 9 72]]
              precision    recall  f1-score   support

           0       0.68      0.41      0.51        46
           1       0.73      0.89      0.80        81

    accuracy                           0.72       127
   macro avg       0.70      0.65      0.66       127
weighted avg       0.71      0.72      0.70       127



* Run through steps 2-4 setting k to 10

In [ ]:
knn = KNeighborsClassifier(n_neighbors=10, weights='uniform')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_train)
y_pred_proba = knn.predict_proba(X_train)
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

* Run through setps 2-4 setting k to 20

In [123]:
knn = KNeighborsClassifier(n_neighbors=20, weights='uniform')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_train)
y_pred_proba = knn.predict_proba(X_train)
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of KNN classifier on training set: 0.70
[[19 27]
 [11 70]]
              precision    recall  f1-score   support

           0       0.63      0.41      0.50        46
           1       0.72      0.86      0.79        81

    accuracy                           0.70       127
   macro avg       0.68      0.64      0.64       127
weighted avg       0.69      0.70      0.68       127



* What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?
  - **Answer**: N_Neighbors = 5 works the best because it restricts the number of neighbors to a reasonable number thus limiting overlap.

### Test 
For both the iris and the titanic data,

* Determine which model (with hyperparameters) performs the best (try reducing the number of features to the top 4 features in terms of information gained for each feature individually).

In [132]:
X = titanic[['pclass','age','sex']]
y = titanic[['survived']]
X = pd.get_dummies(X)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)

X_train.head()

pclass   age  sex_female  sex_male
123       2  32.5           1         0
689       1  15.0           1         0
174       1  56.0           0         1
88        1  23.0           1         0
712       1  48.0           0         1

In [133]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_train)
y_pred_proba = knn.predict_proba(X_train)
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Accuracy of KNN classifier on training set: 0.79
[[30 16]
 [11 70]]
              precision    recall  f1-score   support

           0       0.73      0.65      0.69        46
           1       0.81      0.86      0.84        81

    accuracy                           0.79       127
   macro avg       0.77      0.76      0.76       127
weighted avg       0.78      0.79      0.78       127



* Create a new dataframe with top 4 features.

* Use the top performing algorithm with the metaparameters used in that model. Create the object, fit, transform on in-sample data, and evaluate the results with the training data. Compare your evaluation metrics with those from the original model (with all the features).

* Run your final model on your out-of-sample dataframe (test_df). Evaluate the results.

## Feature Engineering

## Titanic Data
* Create a feature named who, this should be either man, woman, or child. How does including this feature affect your model's performance?
* Create a feature named adult_male that is either a 1 or a 0. How does this affect your model's predictions?

### Iris Data
* Create features named petal_area and sepal_area.